# Generated by Django 4.2.3 on 2023-07-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('price_sqft', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_rank', models.CharField(max_length=100)),
                ('employee_pay', models.CharField(max_length=100)),
                ('years_of_experience', models.CharField(max_length=100)),
                ('employee_picture', models.CharField(max_length=100)),
                ('skill_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('project_manager', models.CharField(max_length=100)),
                ('estimate', models.CharField(max_length=100)),
                ('invoice', models.CharField(max_length=100)),
                ('total_cost', models.CharField(max_length=100)),
                ('type_of_job', models.CharField(max_length=100)),
                ('material_cost', models.CharField(max_length=100)),
                ('labor_cost', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='CEDB.customer')),
                ('employee_id', models.ManyToManyField(db_column='employee_id', related_name='projects', to='CEDB.employee')),
            ],
        ),
    ]
